package me.blockcraft.lobby.commands;

import me.blockcraft.lobby.Lobby;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.ArmorStand;
import org.bukkit.entity.Blaze;
import org.bukkit.entity.EntityType;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;

public class CommandSetholo implements CommandExecutor {
    public static Lobby main;

    public CommandSetholo(final Lobby main) {
        CommandSetholo.main = main;
    }

    public boolean onCommand(final CommandSender sender, final Command cmd, final String alias, final String[] args) {
        final Player p = (Player) sender;
        if (cmd.getName().equalsIgnoreCase("setholo")) {
            if (args.length == 0) {
                p.sendMessage("\u00a78» \u00a7cKorrekte Verwendung \u00a76/setholo <Type>");
            }
            if (args.length == 1) {
                if (args[0].equalsIgnoreCase("Syndicate")) {
                    CommandSetholo.main.getConfig().set("holo.world", p.getLocation().getWorld().getName());
                    CommandSetholo.main.getConfig().set("holo.x", p.getLocation().getX());
                    CommandSetholo.main.getConfig().set("holo.y", p.getLocation().getY());
                    CommandSetholo.main.getConfig().set("holo.z", p.getLocation().getZ());
                    CommandSetholo.main.getConfig().set("holo.yaw", p.getLocation().getYaw());
                    CommandSetholo.main.getConfig().set("holo.pitch", p.getLocation().getPitch());
                    p.sendMessage("\u00a7cServer \u00a78» \u00a77Hologramm gesetzt.");
                    CommandSetholo.main.saveConfig();
                    Location loc;
                    final World world = p.getLocation().getWorld();
                    final double x = p.getLocation().getX();
                    final double y = 33.5;
                    final double z = p.getLocation().getZ();
                    final float yaw = p.getLocation().getYaw();
                    final float pitch = p.getLocation().getPitch();
                    loc = new Location(world, x, y, z, yaw, pitch);
                    final ArmorStand g2 = (ArmorStand) world.spawnEntity(loc, EntityType.ARMOR_STAND);
                    Location loc2;
                    final World world2 = p.getLocation().getWorld();
                    final double x2 = p.getLocation().getX();
                    final double y2 = 33.15;
                    final double z2 = p.getLocation().getZ();
                    final float yaw2 = p.getLocation().getYaw();
                    final float pitch2 = p.getLocation().getPitch();
                    loc2 = new Location(world2, x2, y2, z2, yaw2, pitch2);
                    final ArmorStand g3 = (ArmorStand) world2.spawnEntity(loc2, EntityType.ARMOR_STAND);
                    Location loc3;
                    final World world3 = p.getLocation().getWorld();
                    final double x3 = p.getLocation().getX();
                    final double y3 = 32.85;
                    final double z3 = p.getLocation().getZ();
                    final float yaw3 = p.getLocation().getYaw();
                    final float pitch3 = p.getLocation().getPitch();
                    loc3 = new Location(world3, x3, y3, z3, yaw3, pitch3);
                    final ArmorStand g4 = (ArmorStand) world3.spawnEntity(loc3, EntityType.ARMOR_STAND);
                    Location loc4;
                    final World world4 = p.getLocation().getWorld();
                    final double x4 = p.getLocation().getX();
                    final double y4 = 32.5;
                    final double z4 = p.getLocation().getZ();
                    final float yaw4 = p.getLocation().getYaw();
                    final float pitch4 = p.getLocation().getPitch();
                    loc4 = new Location(world4, x4, y4, z4, yaw4, pitch4);
                    final ArmorStand g5 = (ArmorStand) world4.spawnEntity(loc4, EntityType.ARMOR_STAND);
                    Location loc5;
                    final World world5 = p.getLocation().getWorld();
                    final double x5 = p.getLocation().getX();
                    final double y5 = 34.5;
                    final double z5 = p.getLocation().getZ();
                    final float yaw5 = p.getLocation().getYaw();
                    final float pitch5 = p.getLocation().getPitch();
                    loc5 = new Location(world5, x5, y5, z5, yaw5, pitch5);
                    final ArmorStand g6 = (ArmorStand) world5.spawnEntity(loc5, EntityType.ARMOR_STAND);
                    g6.setCustomNameVisible(false);
                    g6.setGravity(false);
                    g6.setVisible(false);
                    g6.setSmall(true);
                    final ItemStack i = new ItemStack(Material.DIAMOND_HELMET);
                    g6.setHelmet(i);
                    g2.setCanPickupItems(false);
                    g2.setVisible(false);
                    g3.setVisible(false);
                    g4.setVisible(false);
                    g5.setVisible(false);
                    g2.setCustomName("\u00a78● \u00a76\u00a7lSYNDICATE \u00a78●");
                    g2.setCustomNameVisible(true);
                    g2.setGravity(false);
                    g2.setSmall(true);
                    g3.setCustomName("\u00a78- \u00a771vs1 Survivalgames \u00a78-");
                    g3.setCustomNameVisible(true);
                    g3.setGravity(false);
                    g3.setSmall(true);
                    g4.setCustomName("\u00a7everbundene Spieler: \u00a7c54");
                    g4.setCustomNameVisible(true);
                    g4.setGravity(false);
                    g4.setSmall(true);
                    g5.setCustomName("\u00a7eStatus: \u00a7aOK");
                    g5.setCustomNameVisible(true);
                    g5.setGravity(false);
                    g5.setSmall(true);
                }
                if (args[0].equalsIgnoreCase("skypvp")) {
                    CommandSetholo.main.getConfig().set("holo.world", p.getLocation().getWorld().getName());
                    CommandSetholo.main.getConfig().set("holo.x", p.getLocation().getX());
                    CommandSetholo.main.getConfig().set("holo.y", p.getLocation().getY());
                    CommandSetholo.main.getConfig().set("holo.z", p.getLocation().getZ());
                    CommandSetholo.main.getConfig().set("holo.yaw", p.getLocation().getYaw());
                    CommandSetholo.main.getConfig().set("holo.pitch", p.getLocation().getPitch());
                    p.sendMessage("\u00a7cServer \u00a78» \u00a77Hologramm gesetzt.");
                    CommandSetholo.main.saveConfig();
                    Location loc;
                    final World world = p.getLocation().getWorld();
                    final double x = p.getLocation().getX();
                    final double y = 31.7;
                    final double z = p.getLocation().getZ();
                    final float yaw = p.getLocation().getYaw();
                    final float pitch = p.getLocation().getPitch();
                    loc = new Location(world, x, y, z, yaw, pitch);
                    final ArmorStand g2 = (ArmorStand) world.spawnEntity(loc, EntityType.ARMOR_STAND);
                    Location loc2;
                    final World world2 = p.getLocation().getWorld();
                    final double x2 = p.getLocation().getX();
                    final double y2 = 31.35;
                    final double z2 = p.getLocation().getZ();
                    final float yaw2 = p.getLocation().getYaw();
                    final float pitch2 = p.getLocation().getPitch();
                    loc2 = new Location(world2, x2, y2, z2, yaw2, pitch2);
                    final ArmorStand g3 = (ArmorStand) world2.spawnEntity(loc2, EntityType.ARMOR_STAND);
                    Location loc3;
                    final World world3 = p.getLocation().getWorld();
                    final double x3 = p.getLocation().getX();
                    final double y3 = 31.0;
                    final double z3 = p.getLocation().getZ();
                    final float yaw3 = p.getLocation().getYaw();
                    final float pitch3 = p.getLocation().getPitch();
                    loc3 = new Location(world3, x3, y3, z3, yaw3, pitch3);
                    final ArmorStand g4 = (ArmorStand) world3.spawnEntity(loc3, EntityType.ARMOR_STAND);
                    Location loc4;
                    final World world4 = p.getLocation().getWorld();
                    final double x4 = p.getLocation().getX();
                    final double y4 = 30.65;
                    final double z4 = p.getLocation().getZ();
                    final float yaw4 = p.getLocation().getYaw();
                    final float pitch4 = p.getLocation().getPitch();
                    loc4 = new Location(world4, x4, y4, z4, yaw4, pitch4);
                    final ArmorStand g5 = (ArmorStand) world4.spawnEntity(loc4, EntityType.ARMOR_STAND);
                    Location loc5;
                    final World world5 = p.getLocation().getWorld();
                    final double x5 = p.getLocation().getX();
                    final double y5 = 30.3;
                    final double z5 = p.getLocation().getZ();
                    final float yaw5 = p.getLocation().getYaw();
                    final float pitch5 = p.getLocation().getPitch();
                    loc5 = new Location(world5, x5, y5, z5, yaw5, pitch5);
                    final ArmorStand g6 = (ArmorStand) world5.spawnEntity(loc5, EntityType.ARMOR_STAND);
                    g6.setCustomNameVisible(false);
                    g6.setGravity(false);
                    g6.setVisible(false);
                    g6.setSmall(true);
                    g2.setCanPickupItems(false);
                    g2.setVisible(false);
                    g3.setVisible(false);
                    g4.setVisible(false);
                    g5.setVisible(false);
                    g2.setCustomName("\u00a78● \u00a76\u00a7lSKYPVP \u00a78●");
                    g2.setCustomNameVisible(true);
                    g2.setGravity(false);
                    g2.setSmall(true);
                    g3.setCustomName("\u00a78- \u00a77SkyPvP und SkyBlock\u00a78-");
                    g3.setCustomNameVisible(true);
                    g3.setGravity(false);
                    g3.setSmall(true);
                    g4.setCustomName("\u00a78- \u00a77Wächentliche \u00a7bEvents \u00a78-");
                    g4.setCustomNameVisible(true);
                    g4.setGravity(false);
                    g4.setSmall(true);
                    g5.setCustomName("\u00a7eStatus: \u00a7aOK");
                    g5.setCustomNameVisible(true);
                    g5.setGravity(false);
                    g5.setSmall(true);
                }
                if (args[0].equalsIgnoreCase("farm")) {
                    CommandSetholo.main.getConfig().set("holo.world", p.getLocation().getWorld().getName());
                    CommandSetholo.main.getConfig().set("holo.x", p.getLocation().getX());
                    CommandSetholo.main.getConfig().set("holo.y", p.getLocation().getY());
                    CommandSetholo.main.getConfig().set("holo.z", p.getLocation().getZ());
                    CommandSetholo.main.getConfig().set("holo.yaw", p.getLocation().getYaw());
                    CommandSetholo.main.getConfig().set("holo.pitch", p.getLocation().getPitch());
                    p.sendMessage("\u00a7cServer \u00a78» \u00a77Hologramm gesetzt.");
                    CommandSetholo.main.saveConfig();
                    Location loc;
                    final World world = p.getLocation().getWorld();
                    final double x = p.getLocation().getX();
                    final double y = 33.5;
                    final double z = p.getLocation().getZ();
                    final float yaw = p.getLocation().getYaw();
                    final float pitch = p.getLocation().getPitch();
                    loc = new Location(world, x, y, z, yaw, pitch);
                    final ArmorStand g2 = (ArmorStand) world.spawnEntity(loc, EntityType.ARMOR_STAND);
                    Location loc2;
                    final World world2 = p.getLocation().getWorld();
                    final double x2 = p.getLocation().getX();
                    final double y2 = 33.15;
                    final double z2 = p.getLocation().getZ();
                    final float yaw2 = p.getLocation().getYaw();
                    final float pitch2 = p.getLocation().getPitch();
                    loc2 = new Location(world2, x2, y2, z2, yaw2, pitch2);
                    final ArmorStand g3 = (ArmorStand) world2.spawnEntity(loc2, EntityType.ARMOR_STAND);
                    Location loc3;
                    final World world3 = p.getLocation().getWorld();
                    final double x3 = p.getLocation().getX();
                    final double y3 = 32.85;
                    final double z3 = p.getLocation().getZ();
                    final float yaw3 = p.getLocation().getYaw();
                    final float pitch3 = p.getLocation().getPitch();
                    loc3 = new Location(world3, x3, y3, z3, yaw3, pitch3);
                    final ArmorStand g4 = (ArmorStand) world3.spawnEntity(loc3, EntityType.ARMOR_STAND);
                    Location loc4;
                    final World world4 = p.getLocation().getWorld();
                    final double x4 = p.getLocation().getX();
                    final double y4 = 32.5;
                    final double z4 = p.getLocation().getZ();
                    final float yaw4 = p.getLocation().getYaw();
                    final float pitch4 = p.getLocation().getPitch();
                    loc4 = new Location(world4, x4, y4, z4, yaw4, pitch4);
                    final ArmorStand g5 = (ArmorStand) world4.spawnEntity(loc4, EntityType.ARMOR_STAND);
                    Location loc5;
                    final World world5 = p.getLocation().getWorld();
                    final double x5 = p.getLocation().getX();
                    final double y5 = 34.5;
                    final double z5 = p.getLocation().getZ();
                    final float yaw5 = p.getLocation().getYaw();
                    final float pitch5 = p.getLocation().getPitch();
                    loc5 = new Location(world5, x5, y5, z5, yaw5, pitch5);
                    final ArmorStand g6 = (ArmorStand) world5.spawnEntity(loc5, EntityType.ARMOR_STAND);
                    g6.setCustomNameVisible(false);
                    g6.setGravity(false);
                    g6.setVisible(false);
                    g6.setSmall(true);
                    g2.setCanPickupItems(false);
                    g2.setVisible(false);
                    g3.setVisible(false);
                    g4.setVisible(false);
                    g5.setVisible(false);
                    g2.setCustomName("\u00a78● \u00a76\u00a7lFarmWars \u00a78●");
                    g2.setCustomNameVisible(true);
                    g2.setGravity(false);
                    g2.setSmall(true);
                    g3.setCustomName("\u00a78- \u00a77Keine Ahnung xD \u00a78-");
                    g3.setCustomNameVisible(true);
                    g3.setGravity(false);
                    g3.setSmall(true);
                    g4.setCustomName("\u00a7everbundene Spieler: \u00a7c54");
                    g4.setCustomNameVisible(true);
                    g4.setGravity(false);
                    g4.setSmall(true);
                    g5.setCustomName("\u00a7eStatus: \u00a7aOK");
                    g5.setCustomNameVisible(true);
                    g5.setGravity(false);
                    g5.setSmall(true);
                }
                if (args[0].equalsIgnoreCase("shop")) {
                    final Blaze g7 = (Blaze) p.getLocation().getWorld().spawnEntity(p.getLocation(), EntityType.BLAZE);
                    final ArmorStand g8 = (ArmorStand) p.getLocation().getWorld().spawnEntity(p.getLocation(), EntityType.ARMOR_STAND);
                    g7.spigot().isInvulnerable();
                    g7.addPotionEffect(new PotionEffect(PotionEffectType.SLOW, Integer.MAX_VALUE, 255), false);
                    g7.addPotionEffect(new PotionEffect(PotionEffectType.JUMP, Integer.MAX_VALUE, -25000));
                    g8.setVisible(false);
                    g8.setCustomNameVisible(true);
                    g8.setSmall(true);
                    g8.setCustomName("\u00a78● \u00a79LOBBY-SHOP \u00a78●");
                    g8.setGravity(false);
                    g7.setPassenger(g8);
                    CommandSetholo.main.getConfig().set("blaze.world", p.getLocation().getWorld().getName());
                    CommandSetholo.main.getConfig().set("blaze.x", p.getLocation().getX());
                    CommandSetholo.main.getConfig().set("blaze.y", p.getLocation().getY());
                    CommandSetholo.main.getConfig().set("blaze.z", p.getLocation().getZ());
                    CommandSetholo.main.getConfig().set("blaze.yaw", p.getLocation().getYaw());
                    CommandSetholo.main.getConfig().set("blaze.pitch", p.getLocation().getPitch());
                    CommandSetholo.main.saveConfig();
                    p.sendMessage("\u00a7cServer \u00a78» \u00a77 gesetzt.");
                }
            }
        }
        return false;
    }
}
